blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ DÃºvidas e Suporte
    url: https://github.com/HDEV-Desenvolvimento-de-Casa/hdev-hub/discussions
    about: Use as Discussions para fazer perguntas e obter ajuda da comunidade

